import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { tokens } from '../../docs/design-system/tokens.ts'

type Tree = { readonly [key: string]: string | Tree }
export function flatten(tree: Tree, prefix = ''): [string, string][] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const name = prefix ? `${prefix}-${key}` : key
    return typeof value === 'string' ? [[name, value] as [string, string]] : flatten(value, name)
  })
}
export function renderTokens() {
  const entries = flatten(tokens)
  const colors = entries.filter(([name]) => /^(brand|surface|text|border|action|feedback)-/.test(name) && !/-(width|offset)$/.test(name))
  const theme = [
    ...Object.keys(tokens.typography.size).map(name => [`text-${name}`, `typography-size-${name}`]),
    ...Object.keys(tokens.typography.weight).map(name => [`font-weight-${name}`, `typography-weight-${name}`]),
    ...Object.keys(tokens.typography.line).map(name => [`leading-${name}`, `typography-line-${name}`]),
    ...Object.keys(tokens.radius).map(name => [`radius-${name}`, `radius-${name}`]),
    ...Object.keys(tokens.elevation).map(name => [`shadow-${name}`, `elevation-${name}`]),
    ['container-app', 'layout-container'], ['container-reading', 'layout-reading'],
    ['spacing-target', 'layout-target'], ['font-sans', 'typography-family'], ['spacing', 'space-1'],
  ]
  return '/* Generated by pnpm tokens:generate from docs/design-system/tokens.ts. Do not edit. */\n:root {\n'
    + entries.map(([name, value]) => `  --ds-${name}: ${value};`).join('\n')
    + '\n}\n\n@theme inline {\n'
    + colors.map(([name]) => `  --color-${name}: var(--ds-${name});`).join('\n')
    + '\n' + theme.map(([name, token]) => `  --${name}: var(--ds-${token});`).join('\n') + '\n}\n'
}
export const outputPath = fileURLToPath(new URL('../src/styles/tokens.generated.css', import.meta.url))
export async function syncTokens(check: boolean, path = outputPath) {
  const expected = renderTokens()
  if (check) {
    const actual = await readFile(path, 'utf8').catch((error: unknown) => {
      if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return ''
      throw error
    })
    if (actual !== expected) throw new Error('Tokens CSS desatualizados. Execute pnpm tokens:generate e versione a saída.')
  } else {
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, expected)
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try { await syncTokens(process.argv.includes('--check')) }
  catch (error) { console.error(error instanceof Error ? error.message : error); process.exitCode = 1 }
}
